global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scheme: http
  
  - job_name: 'statsd-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: 
        - 'statsd-exporter:9102'
  
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']